# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workspace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='workspace.proto',
  package='chaoshub.workspace',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fworkspace.proto\x12\x12\x63haoshub.workspace\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"%\n\tWorkspace\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n\x0b\x43reateReply\x12\x30\n\tworkspace\x18\x02 \x01(\x0b\x32\x1d.chaoshub.workspace.Workspace\"D\n\x10TerminateRequest\x12\x30\n\tworkspace\x18\x01 \x01(\x0b\x32\x1d.chaoshub.workspace.Workspace\"\x10\n\x0eTerminateReply\":\n\x10GetByUserRequest\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.chaoshub.workspace.User\"C\n\x0eGetByUserReply\x12\x31\n\nworkspaces\x18\x01 \x03(\x0b\x32\x1d.chaoshub.workspace.Workspace\"?\n\x0bSaveRequest\x12\x30\n\tworkspace\x18\x01 \x01(\x0b\x32\x1d.chaoshub.workspace.Workspace\"\x0b\n\tSaveReply\"A\n\rRemoveRequest\x12\x30\n\tworkspace\x18\x01 \x01(\x0b\x32\x1d.chaoshub.workspace.Workspace\"\r\n\x0bRemoveReply2\x88\x02\n\x10WorkspaceService\x12L\n\x06\x43reate\x12!.chaoshub.workspace.CreateRequest\x1a\x1f.chaoshub.workspace.CreateReply\x12R\n\x06\x44\x65lete\x12$.chaoshub.workspace.TerminateRequest\x1a\".chaoshub.workspace.TerminateReply\x12R\n\x06\x42yUser\x12$.chaoshub.workspace.GetByUserRequest\x1a\".chaoshub.workspace.GetByUserReply2\xaf\x01\n\x17WorkspaceStorageService\x12\x46\n\x04Save\x12\x1f.chaoshub.workspace.SaveRequest\x1a\x1d.chaoshub.workspace.SaveReply\x12L\n\x06Remove\x12!.chaoshub.workspace.RemoveRequest\x1a\x1f.chaoshub.workspace.RemoveReplyb\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='chaoshub.workspace.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chaoshub.workspace.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='chaoshub.workspace.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=71,
)


_WORKSPACE = _descriptor.Descriptor(
  name='Workspace',
  full_name='chaoshub.workspace.Workspace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chaoshub.workspace.Workspace.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='chaoshub.workspace.Workspace.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=110,
)


_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='chaoshub.workspace.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chaoshub.workspace.CreateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=141,
)


_CREATEREPLY = _descriptor.Descriptor(
  name='CreateReply',
  full_name='chaoshub.workspace.CreateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace', full_name='chaoshub.workspace.CreateReply.workspace', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=206,
)


_TERMINATEREQUEST = _descriptor.Descriptor(
  name='TerminateRequest',
  full_name='chaoshub.workspace.TerminateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace', full_name='chaoshub.workspace.TerminateRequest.workspace', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=276,
)


_TERMINATEREPLY = _descriptor.Descriptor(
  name='TerminateReply',
  full_name='chaoshub.workspace.TerminateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=294,
)


_GETBYUSERREQUEST = _descriptor.Descriptor(
  name='GetByUserRequest',
  full_name='chaoshub.workspace.GetByUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='chaoshub.workspace.GetByUserRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=354,
)


_GETBYUSERREPLY = _descriptor.Descriptor(
  name='GetByUserReply',
  full_name='chaoshub.workspace.GetByUserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspaces', full_name='chaoshub.workspace.GetByUserReply.workspaces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=423,
)


_SAVEREQUEST = _descriptor.Descriptor(
  name='SaveRequest',
  full_name='chaoshub.workspace.SaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace', full_name='chaoshub.workspace.SaveRequest.workspace', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=488,
)


_SAVEREPLY = _descriptor.Descriptor(
  name='SaveReply',
  full_name='chaoshub.workspace.SaveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=501,
)


_REMOVEREQUEST = _descriptor.Descriptor(
  name='RemoveRequest',
  full_name='chaoshub.workspace.RemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace', full_name='chaoshub.workspace.RemoveRequest.workspace', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=568,
)


_REMOVEREPLY = _descriptor.Descriptor(
  name='RemoveReply',
  full_name='chaoshub.workspace.RemoveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=583,
)

_CREATEREPLY.fields_by_name['workspace'].message_type = _WORKSPACE
_TERMINATEREQUEST.fields_by_name['workspace'].message_type = _WORKSPACE
_GETBYUSERREQUEST.fields_by_name['user'].message_type = _USER
_GETBYUSERREPLY.fields_by_name['workspaces'].message_type = _WORKSPACE
_SAVEREQUEST.fields_by_name['workspace'].message_type = _WORKSPACE
_REMOVEREQUEST.fields_by_name['workspace'].message_type = _WORKSPACE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Workspace'] = _WORKSPACE
DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['CreateReply'] = _CREATEREPLY
DESCRIPTOR.message_types_by_name['TerminateRequest'] = _TERMINATEREQUEST
DESCRIPTOR.message_types_by_name['TerminateReply'] = _TERMINATEREPLY
DESCRIPTOR.message_types_by_name['GetByUserRequest'] = _GETBYUSERREQUEST
DESCRIPTOR.message_types_by_name['GetByUserReply'] = _GETBYUSERREPLY
DESCRIPTOR.message_types_by_name['SaveRequest'] = _SAVEREQUEST
DESCRIPTOR.message_types_by_name['SaveReply'] = _SAVEREPLY
DESCRIPTOR.message_types_by_name['RemoveRequest'] = _REMOVEREQUEST
DESCRIPTOR.message_types_by_name['RemoveReply'] = _REMOVEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.User)
  ))
_sym_db.RegisterMessage(User)

Workspace = _reflection.GeneratedProtocolMessageType('Workspace', (_message.Message,), dict(
  DESCRIPTOR = _WORKSPACE,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.Workspace)
  ))
_sym_db.RegisterMessage(Workspace)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.CreateRequest)
  ))
_sym_db.RegisterMessage(CreateRequest)

CreateReply = _reflection.GeneratedProtocolMessageType('CreateReply', (_message.Message,), dict(
  DESCRIPTOR = _CREATEREPLY,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.CreateReply)
  ))
_sym_db.RegisterMessage(CreateReply)

TerminateRequest = _reflection.GeneratedProtocolMessageType('TerminateRequest', (_message.Message,), dict(
  DESCRIPTOR = _TERMINATEREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.TerminateRequest)
  ))
_sym_db.RegisterMessage(TerminateRequest)

TerminateReply = _reflection.GeneratedProtocolMessageType('TerminateReply', (_message.Message,), dict(
  DESCRIPTOR = _TERMINATEREPLY,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.TerminateReply)
  ))
_sym_db.RegisterMessage(TerminateReply)

GetByUserRequest = _reflection.GeneratedProtocolMessageType('GetByUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETBYUSERREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.GetByUserRequest)
  ))
_sym_db.RegisterMessage(GetByUserRequest)

GetByUserReply = _reflection.GeneratedProtocolMessageType('GetByUserReply', (_message.Message,), dict(
  DESCRIPTOR = _GETBYUSERREPLY,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.GetByUserReply)
  ))
_sym_db.RegisterMessage(GetByUserReply)

SaveRequest = _reflection.GeneratedProtocolMessageType('SaveRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAVEREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.SaveRequest)
  ))
_sym_db.RegisterMessage(SaveRequest)

SaveReply = _reflection.GeneratedProtocolMessageType('SaveReply', (_message.Message,), dict(
  DESCRIPTOR = _SAVEREPLY,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.SaveReply)
  ))
_sym_db.RegisterMessage(SaveReply)

RemoveRequest = _reflection.GeneratedProtocolMessageType('RemoveRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.RemoveRequest)
  ))
_sym_db.RegisterMessage(RemoveRequest)

RemoveReply = _reflection.GeneratedProtocolMessageType('RemoveReply', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEREPLY,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:chaoshub.workspace.RemoveReply)
  ))
_sym_db.RegisterMessage(RemoveReply)



_WORKSPACESERVICE = _descriptor.ServiceDescriptor(
  name='WorkspaceService',
  full_name='chaoshub.workspace.WorkspaceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=586,
  serialized_end=850,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='chaoshub.workspace.WorkspaceService.Create',
    index=0,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=_CREATEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='chaoshub.workspace.WorkspaceService.Delete',
    index=1,
    containing_service=None,
    input_type=_TERMINATEREQUEST,
    output_type=_TERMINATEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ByUser',
    full_name='chaoshub.workspace.WorkspaceService.ByUser',
    index=2,
    containing_service=None,
    input_type=_GETBYUSERREQUEST,
    output_type=_GETBYUSERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKSPACESERVICE)

DESCRIPTOR.services_by_name['WorkspaceService'] = _WORKSPACESERVICE


_WORKSPACESTORAGESERVICE = _descriptor.ServiceDescriptor(
  name='WorkspaceStorageService',
  full_name='chaoshub.workspace.WorkspaceStorageService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=853,
  serialized_end=1028,
  methods=[
  _descriptor.MethodDescriptor(
    name='Save',
    full_name='chaoshub.workspace.WorkspaceStorageService.Save',
    index=0,
    containing_service=None,
    input_type=_SAVEREQUEST,
    output_type=_SAVEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='chaoshub.workspace.WorkspaceStorageService.Remove',
    index=1,
    containing_service=None,
    input_type=_REMOVEREQUEST,
    output_type=_REMOVEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKSPACESTORAGESERVICE)

DESCRIPTOR.services_by_name['WorkspaceStorageService'] = _WORKSPACESTORAGESERVICE

# @@protoc_insertion_point(module_scope)
