language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
