# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import activity_pb2 as activity_dot_activity__pb2


class ActivityServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Record = channel.unary_unary(
        '/chaosplatform.activity.ActivityService/Record',
        request_serializer=activity_dot_activity__pb2.RecordRequest.SerializeToString,
        response_deserializer=activity_dot_activity__pb2.RecordReply.FromString,
        )
    self.GetByUser = channel.unary_unary(
        '/chaosplatform.activity.ActivityService/GetByUser',
        request_serializer=activity_dot_activity__pb2.GetByUserRequest.SerializeToString,
        response_deserializer=activity_dot_activity__pb2.GetByUserReply.FromString,
        )
    self.GetByOrg = channel.unary_unary(
        '/chaosplatform.activity.ActivityService/GetByOrg',
        request_serializer=activity_dot_activity__pb2.GetByOrgRequest.SerializeToString,
        response_deserializer=activity_dot_activity__pb2.GetByOrgReply.FromString,
        )
    self.GetByWorkspace = channel.unary_unary(
        '/chaosplatform.activity.ActivityService/GetByWorkspace',
        request_serializer=activity_dot_activity__pb2.GetByWorkspaceRequest.SerializeToString,
        response_deserializer=activity_dot_activity__pb2.GetByWorkspaceReply.FromString,
        )


class ActivityServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Record(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetByOrg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetByWorkspace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ActivityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Record': grpc.unary_unary_rpc_method_handler(
          servicer.Record,
          request_deserializer=activity_dot_activity__pb2.RecordRequest.FromString,
          response_serializer=activity_dot_activity__pb2.RecordReply.SerializeToString,
      ),
      'GetByUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetByUser,
          request_deserializer=activity_dot_activity__pb2.GetByUserRequest.FromString,
          response_serializer=activity_dot_activity__pb2.GetByUserReply.SerializeToString,
      ),
      'GetByOrg': grpc.unary_unary_rpc_method_handler(
          servicer.GetByOrg,
          request_deserializer=activity_dot_activity__pb2.GetByOrgRequest.FromString,
          response_serializer=activity_dot_activity__pb2.GetByOrgReply.SerializeToString,
      ),
      'GetByWorkspace': grpc.unary_unary_rpc_method_handler(
          servicer.GetByWorkspace,
          request_deserializer=activity_dot_activity__pb2.GetByWorkspaceRequest.FromString,
          response_serializer=activity_dot_activity__pb2.GetByWorkspaceReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chaosplatform.activity.ActivityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
